apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testing-node-template
  annotations:
    github.com/project-slug: jescalada/testing-node-template
spec:
  type: other
  lifecycle: unknown
  owner: guests
